language: node_js
sudo: required
dist: trusty
fail_fast: true
addons:
  firefox: '46.0'
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
node_js:
  - '6'
  - '5'
  - '4'
before_script:
  - npm install -g bower web-components-tester
  - bower install
script:
  - xvfb-run wct